name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping render service
        run: curl -s -o /dev/null -w "%{http_code}\n" https://linux-vnc-github.onrender.com
